### PR TITLE
Remove extraneous semicolons after end of namespaces.

### PR DESCRIPTION
**Pull request by mlang**

### CODE REVIEW

**Comment by gruenich** [comment]
Is there a reason not merge this trivial fix? Maybe @mlang should rebase the commit to the tip of master?

**Comment by mwestphal** [comment]
MR should be opened on gitlab, read this : https://gitlab.kitware.com/paraview/paraview/-/blob/master/Documentation/dev/git/develop.md

**Comment by gruenich** [comment]
I tried to apply the patch to the tip of master. None of the changes could be directly used. I think it would be best to close this MR, as it is not worth to invest too much time.

**Comment by mwestphal** [comment]
Fair enough, could you close it ?

**Comment by gruenich** [comment]
No, I don't have the right to close other people's MR. Could you close it or ask someone who can?

**Comment by mwestphal** [comment]
@utkarshayachit @mlang

**Pull request closed without merging**
